name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  MONGODB_DB_NAME: gb-dbase
jobs:
  test:
    environment:
      MONGODB_CLUSTER_ADDRESS: cluster0.djauofb.mongodb.net
      # We can not hard-code the secret pw in workflow file. so have to find an alternative way to secure the password
      # MONGODB_USERNAME: indrajith
      # MONGODB_PASSWORD: pLLXwaRzvpjFSJbk
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}     
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "${{ env.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo " ${{ env.MONGODB_CLUSTER_ADDRESS }}"
          echo " ${{ env.MONGODB_DB_NAME }} "
